name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_linux:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install shellcheck
      run: |
        echo "TERM=xterm-256color" >> $GITHUB_ENV
        sudo apt-get install shellcheck
    - name: Lint
      run: ./test
